services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: godfather-backend
    environment:
      SERVER_PORT: "8081"
      MANAGEMENT_SERVER_PORT: "9091"
      DB_HOST: godfather-mysql
      DB_PORT: "3306"
      DB_USERNAME: root
      DB_PASSWORD: admin
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_PASSWORD: admin 
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8081:8081"
      - "9091:9091"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: godfather-frontend
    ports:
      - "8008:80"
    depends_on:
      - backend
    restart: unless-stopped

  mysql:
    image: mysql:8.4.7
    container_name: godfather-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: family_hub
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:8.4.0
    container_name: godfather-redis
    command: redis-server --requirepass admin
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "admin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mysql-data:
  redis-data:
