-- 更新任务分类注释，添加 TALENT（特长）类型

ALTER TABLE task_template
    MODIFY COLUMN category VARCHAR(16) NOT NULL COMMENT '分类：STUDY/SPORT/CHORE/HOBBY/TALENT/OTHER';

ALTER TABLE daily_task
    MODIFY COLUMN category VARCHAR(16) NOT NULL COMMENT '分类：STUDY/SPORT/CHORE/HOBBY/TALENT/OTHER';
